In [28]:
import numpy as np
import pandas as pd
import tensorflow_datasets as tfds
import tensorflow_hub as hub
import tensorflow as tf

In [3]:
import matplotlib.pyplot as plt


def plot_graphs(history, metric):
  plt.plot(history.history[metric])
  plt.plot(history.history['val_'+metric], '')
  plt.xlabel("Epochs")
  plt.ylabel(metric)
  plt.legend([metric, 'val_'+metric])

In [4]:
train_data_set = pd.read_csv("/home/mdirfan-code/projects/Sentimeter-v1.0/BERT_Model/Datasets/Training_dataset.csv")
train_data_set

Unnamed: 0   sentiment  \
0           49647  Irrelevant   
1           43676    Positive   
2           55915    Negative   
3           14927    Positive   
4           44039  Irrelevant   
...           ...         ...   
59191       37541    Negative   
59192        6332     Neutral   
59193       55392    Negative   
59194         864    Positive   
59195       15956  Irrelevant   

                                              tweet_text  
0      Last Weekend league for Fifa 20 Glad I could f...  
1               omg i'm so excited to watch dk play pubg  
2                      all others who have problems with  
3                                                     in  
4      minho felix de jeongin sucked at pubg pretty h...  
...                                                  ...  
59191                                                you  
59192             I'm not even going to show a 7 2 loss.  
59193                    Fuck this call of duty update..  
59194  I should get up feed my dogs such that way whe...  
59195                      Welcome to The International!  

[59196 rows x 3 columns]

In [5]:
test_data_set = pd.read_csv("/home/mdirfan-code/projects/Sentimeter-v1.0/BERT_Model/Datasets/Testing_dataset.csv")
test_data_set

Unnamed: 0   sentiment  \
0           61413  Irrelevant   
1           44887  Irrelevant   
2           73662     Neutral   
3           36694     Neutral   
4            2308    Negative   
...           ...         ...   
14795       12630    Negative   
14796       49615    Negative   
14797       12322    Negative   
14798        4355  Irrelevant   
14799       52612    Positive   

                                              tweet_text  
0      Looks to me like he failed to check out the wa...  
1      Wow it takes all sorts of crazy people out the...  
2      Nvidia Unveils The World s Fastest Gaming Moni...  
3      Huge radio play here. Reinvention Corporate Ev...  
4                             SO I HAPPY WHO ABOUT THIS.  
...                                                  ...  
14795   where is all my Mamba Edition extras? I m bee...  
14796             Sell 700k fifa coins fucking this game  
14797   107 for a four game break and I can't even ev...  
14798  has called me a madman.. I understood right fr...  
14799     RDR2 at 31m makes really this boy super happy.  

[14800 rows x 3 columns]

In [6]:
test_data_set.drop('Unnamed: 0',axis=1,inplace=True)
test_data_set

sentiment                                         tweet_text
0      Irrelevant  Looks to me like he failed to check out the wa...
1      Irrelevant  Wow it takes all sorts of crazy people out the...
2         Neutral  Nvidia Unveils The World s Fastest Gaming Moni...
3         Neutral  Huge radio play here. Reinvention Corporate Ev...
4        Negative                         SO I HAPPY WHO ABOUT THIS.
...           ...                                                ...
14795    Negative   where is all my Mamba Edition extras? I m bee...
14796    Negative             Sell 700k fifa coins fucking this game
14797    Negative   107 for a four game break and I can't even ev...
14798  Irrelevant  has called me a madman.. I understood right fr...
14799    Positive     RDR2 at 31m makes really this boy super happy.

[14800 rows x 2 columns]

In [7]:
train_data_set.drop(['Unnamed: 0'],axis=1,inplace=True)
train_data_set


sentiment                                         tweet_text
0      Irrelevant  Last Weekend league for Fifa 20 Glad I could f...
1        Positive           omg i'm so excited to watch dk play pubg
2        Negative                  all others who have problems with
3        Positive                                                 in
4      Irrelevant  minho felix de jeongin sucked at pubg pretty h...
...           ...                                                ...
59191    Negative                                                you
59192     Neutral             I'm not even going to show a 7 2 loss.
59193    Negative                    Fuck this call of duty update..
59194    Positive  I should get up feed my dogs such that way whe...
59195  Irrelevant                      Welcome to The International!

[59196 rows x 2 columns]

In [72]:
train_dataset = tf.data.Dataset.from_tensor_slices((train_data_set['tweet_text'].values,train_data_set['sentiment'].values))
test_dataset = tf.data.Dataset.from_tensor_slices((test_data_set['tweet_text'].values,test_data_set['sentiment'].values))

In [73]:
train_data_set['sentiment'].value_counts()

Negative      17978
Positive      16536
Neutral       14503
Irrelevant    10179
Name: sentiment, dtype: int64

In [74]:
table = tf.lookup.StaticHashTable(
    initializer = tf.lookup.KeyValueTensorInitializer(
        keys = tf.constant([ 'Negative','Positive', 'Neutral', 'Irrelevant']),
        values=tf.constant([0,1,2,3])
    ),
    default_value=tf.constant(-1),
    name = "target_encoding"
)

@tf.function
def target(x):
    return table.lookup(x)
    

In [75]:
def show_batch(dataset, size=5):
    for batch, label in dataset.take(size):
        print(batch.numpy())
        print(target(label).numpy())

In [121]:
show_batch(train_dataset,6)

b'Last Weekend league for Fifa 20 Glad I could finish strong . . Birthday Mbappe and TOTS de Bruyne were absolutely clutch . pic.twitter.com n1766sVgP9'
3
b"omg i'm so excited to watch dk play pubg"
1
b'all others who have problems with'
0
b'in'
1
b"minho felix de jeongin sucked at pubg pretty hard today I'm just.. I'm less different than them at 1 thing"
3
b"I appreciate any advice suggestions on this pleeeeease if it's doing hot noodle canister in! All game action was smooth before. This choppy capture is not good. It was fine capturing in OBS before the Nvidia driver update for my RTX GPUs already NERDIOD help NEEDED! "
0


In [77]:
def fetch(text, labels):
    return text, tf.one_hot(target(labels),4)

In [78]:
train_data_f = train_dataset.map(fetch)
test_data_f = test_dataset.map(fetch)

In [79]:
next(iter(train_data_f))

(<tf.Tensor: shape=(), dtype=string, numpy=b'Last Weekend league for Fifa 20 Glad I could finish strong . . Birthday Mbappe and TOTS de Bruyne were absolutely clutch . pic.twitter.com n1766sVgP9'>,
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 0., 1.], dtype=float32)>)

In [27]:
train_data, train_labels = next(iter(train_data_f.batch(5)))
train_data, train_labels

(<tf.Tensor: shape=(5,), dtype=string, numpy=
 array([b'Last Weekend league for Fifa 20 Glad I could finish strong . . Birthday Mbappe and TOTS de Bruyne were absolutely clutch . pic.twitter.com n1766sVgP9',
        b"omg i'm so excited to watch dk play pubg",
        b'all others who have problems with', b'in',
        b"minho felix de jeongin sucked at pubg pretty hard today I'm just.. I'm less different than them at 1 thing"],
       dtype=object)>,
 <tf.Tensor: shape=(5, 4), dtype=float32, numpy=
 array([[0., 0., 0., 1.],
        [1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.],
        [0., 0., 0., 1.]], dtype=float32)>)

In [30]:
# embedding = "https://tfhub.dev/google/tf2-preview/nnlm-en-dim128/1"
# hub_layer = hub.KerasLayer(embedding, output_shape=[128], input_shape=[],
#                             dtype = tf.string, trainable= True
#     )
# hub_layer(train_data[:1])

In [67]:
from sklearn.utils import class_weight

class_weights = list(class_weight.compute_class_weight('balanced', classes = np.unique(train_data_set['sentiment']) ,y=train_data_set['sentiment']))

In [68]:
class_weights
# np.unique(train_data_set['sentiment'])

[1.4538756262894195,
 0.8231727667148737,
 1.0204095704337033,
 0.8949564586357039]

In [71]:
class_weights.sort()
np.unique(train_data_set['sentiment'])

array(['Irrelevant', 'Negative', 'Neutral', 'Positive'], dtype=object)

In [65]:
weights = {}
for index, weight in enumerate(class_weights):
    weights[index] = weight
weights


{0: 0.8231727667148737,
 1: 0.8949564586357039,
 2: 1.0204095704337033,
 3: 1.4538756262894195}

In [95]:
BUFFER_SIZE = 10000
BATCH_SIZE = 64
train_data_f = train_data_f.shuffle(BUFFER_SIZE).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
test_data_f = test_data_f.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

In [96]:
for example, label in train_data_f.take(1):
    print('texts: ', example.numpy())
    print()
    print('labels: ', label.numpy())

texts:  [b' ParthaC97655126 Thanks for entering Grand Summoners.. Watch the video to see if you won a 100 Amazon gift card!. Retweet everyday for another chance to win!... Play GS Global now for a FREE. 5 Golden Kamuy Unit!.'
 b'There has never been a better reminder to change your login data . . '
 b"for letting you know many'll be buying no ps5 at launch but its people really having trouble picking that box art for the Xbox Series X. Sure there's plenty neat descriptors but it's not very confusing???"
 b"The best game I've played in the last few years is Red Dead Redeemption 2. One of the best games I've ever played."
 b'I swear man free to play mobile games servers are 100x better than out of duty servers'
 b'Switching to PlayStation when PS5 comes out. Fuck '
 b'Cyprus The Fuck Out!!! Cyprus 30001189 has just joined the Kingdom at Mixmixer.com deduke'
 b'Black Ops is coming out soon and I had great Cold War era Era vibes and I love every second of them.'
 b'Honk. . RhandlerR pic.tw

In [80]:
VOCAB_SIZE = 1000
encoder = tf.keras.layers.TextVectorization(max_tokens = VOCAB_SIZE)
encoder.adapt(train_data_f.map(lambda text, label:text))

In [81]:
vocab = np.array(encoder.get_vocabulary())
vocab[:12]

array(['', '[UNK]', 'the', 'i', 'to', 'and', 'a', 'of', 'is', 'for', 'in',
       'this'], dtype='<U19')

In [82]:
example = ["this is my game", "I love Myself more than anything","why me nivea"]
encoded_example = encoder(example)[:3].numpy()
encoded_example

array([[ 11,   8,  15,  18,   0,   0],
       [  3,  58, 491,  63, 132, 370],
       [ 71,  20,   1,   0,   0,   0]])

In [97]:
model = tf.keras.Sequential([
    encoder,
    tf.keras.layers.Embedding(
        input_dim=1000,
        output_dim=64,
        # Use masking to handle the variable sequence lengths
        mask_zero=True),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(4,activation='softmax')
])



In [84]:
print([layer.supports_masking for layer in model.layers])

[False, True, True, True, True]


In [98]:
sample_text = ('The movie was cool. The animation and the graphics '
               'were out of this world. I would recommend this movie.')
predictions = model.predict(train_data_f.take(1))
print(predictions[0])
# train_data_f.take(1)

[0.24995995 0.24947248 0.24979737 0.25077015]


In [99]:
padding = "the " * 2000
predictions = model.predict(np.array([sample_text, padding]))
print(predictions[0])

[0.25021288 0.25034788 0.24846135 0.25097784]


In [100]:
model.compile(loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
              optimizer=tf.keras.optimizers.Adam(1e-4),
              metrics=['accuracy'])

In [88]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 text_vectorization_1 (TextV  (None, None)             0         
 ectorization)                                                   
                                                                 
 embedding_2 (Embedding)     (None, None, 64)          64000     
                                                                 
 bidirectional_2 (Bidirectio  (None, 128)              66048     
 nal)                                                            
                                                                 
 dense_4 (Dense)             (None, 64)                8256      
                                                                 
 dense_5 (Dense)             (None, 4)                 260       
                                                                 
Total params: 138,564
Trainable params: 138,564
Non-tr

In [125]:
history = model.fit(train_data_f,epochs=25,validation_data=test_data_f,verbose=1,class_weight=weights)

# model.summary()

Epoch 1/25
925/925 [==============================] - 50s 53ms/step - loss: 0.6066 - accuracy: 0.7568 - val_loss: 0.8470 - val_accuracy: 0.6811
Epoch 2/25
925/925 [==============================] - 51s 54ms/step - loss: 0.5998 - accuracy: 0.7613 - val_loss: 0.8470 - val_accuracy: 0.6797
Epoch 3/25
925/925 [==============================] - 52s 55ms/step - loss: 0.5933 - accuracy: 0.7623 - val_loss: 0.8456 - val_accuracy: 0.6826
Epoch 4/25
925/925 [==============================] - 52s 55ms/step - loss: 0.5962 - accuracy: 0.7623 - val_loss: 0.8466 - val_accuracy: 0.6860
Epoch 5/25
925/925 [==============================] - 53s 56ms/step - loss: 0.5792 - accuracy: 0.7694 - val_loss: 0.8534 - val_accuracy: 0.6864
Epoch 6/25
925/925 [==============================] - 51s 54ms/step - loss: 0.5716 - accuracy: 0.7734 - val_loss: 0.8456 - val_accuracy: 0.6892
Epoch 7/25
925/925 [==============================] - 52s 54ms/step - loss: 0.5659 - accuracy: 0.7734 - val_loss: 0.8586 - val_accuracy:

In [103]:
classes = [ 'Negative','Positive', 'Neutral', 'Irrelevant']

In [120]:
classes[model.predict(np.array(["omg i'm so excited to watch dk play pubg"])).argmax()]

'Positive'

In [123]:

classes[model.predict(np.array(["The best game I've played in the last few years is Red Dead Redeemption 2. One of the best games I've ever played."])).argmax()]

'Positive'